### ISSUE TITLE
don't launch jar

### ISSUE THREAD

**Issue by curious-man** [Kecon/JSocksProxy#20]
After the assembly using the command `maven install`.  I try to run the heat, but in return I get an error :
`$ java -jar jsocksproxy-3.0.0-SNAPSHOT.jar
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at nu.najt.kecon.jsocksproxy.JSocksProxy.<clinit>(JSocksProxy.java:71)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
Exception in thread "main"
`

**Comment by curious-man** [comment]
Progress of the command :
`"C:\Program Files\Java\jdk1.8.0_161\bin\java" -Dmaven.multiModuleProjectDirectory=C:\projects\JSocksProxy "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\plugins\maven\lib\maven3\bin\m2.conf" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\lib\idea_rt.jar=51250:C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2018.1 install -f pom.xml
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jsocksproxy 3.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (prepare-agent) @ jsocksproxy ---
[INFO] argLine set to -javaagent:C:\\Users\\egor\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\projects\\JSocksProxy\\target\\jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jsocksproxy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ jsocksproxy ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jsocksproxy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\projects\JSocksProxy\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ jsocksproxy ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ jsocksproxy ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running nu.najt.kecon.jsocksproxy.socks4.CommandTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 s - in nu.najt.kecon.jsocksproxy.socks4.CommandTest
[INFO] Running nu.najt.kecon.jsocksproxy.socks5.AddressTypeTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 s - in nu.najt.kecon.jsocksproxy.socks5.AddressTypeTest
[INFO] Running nu.najt.kecon.jsocksproxy.socks5.CommandTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in nu.najt.kecon.jsocksproxy.socks5.CommandTest
[INFO] Running nu.najt.kecon.jsocksproxy.socks5.SocksImplementation5Test
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.939 s - in nu.najt.kecon.jsocksproxy.socks5.SocksImplementation5Test
[INFO] Running nu.najt.kecon.jsocksproxy.socks5.StatusTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 s - in nu.najt.kecon.jsocksproxy.socks5.StatusTest
[INFO] Running nu.najt.kecon.jsocksproxy.utils.StringUtilsTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 s - in nu.najt.kecon.jsocksproxy.utils.StringUtilsTest
[INFO] Running nu.najt.kecon.jsocksproxy.ListeningThreadTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.265 s - in nu.najt.kecon.jsocksproxy.ListeningThreadTest
[INFO] Running nu.najt.kecon.jsocksproxy.socks4.SocksImplementation4Test
20:58:40.332 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Failed to connected to 66.102.7.99:80, result 0x5b
20:58:40.356 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Established tunnel
20:58:40.381 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Shutdown connection
20:58:40.436 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Illegal command
nu.najt.kecon.jsocksproxy.IllegalCommandException: Unknown command command: 0x5
	at nu.najt.kecon.jsocksproxy.socks4.Command.valueOf(Command.java:63) ~[classes/:na]
	at nu.najt.kecon.jsocksproxy.socks4.SocksImplementation4.run(SocksImplementation4.java:84) ~[classes/:na]
	at nu.najt.kecon.jsocksproxy.socks4.SocksImplementation4Test.testRunConnectUnknownCommand(SocksImplementation4Test.java:237) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79) [mockito-core-2.18.3.jar:na]
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85) [mockito-core-2.18.3.jar:na]
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39) [mockito-core-2.18.3.jar:na]
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163) [mockito-core-2.18.3.jar:na]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:352) [surefire-junit47-2.20.jar:2.20]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC$1.run(ParallelComputerBuilder.java:595) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157) [surefire-junit47-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386) [surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323) [surefire-booter-2.20.jar:2.20]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143) [surefire-booter-2.20.jar:2.20]
20:58:40.448 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Established tunnel
20:58:40.454 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Shutdown connection
20:58:40.478 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Established tunnel
20:58:40.484 [main] [c:1.2.3.4:0] [ss:5.6.7.8:0] [s:] INFO  nu.najt.kecon.jsocksproxy.socks4 - Shutdown connection
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.224 s - in nu.najt.kecon.jsocksproxy.socks4.SocksImplementation4Test
[INFO] Running nu.najt.kecon.jsocksproxy.TunnelThreadTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 s - in nu.najt.kecon.jsocksproxy.TunnelThreadTest
[INFO] Running nu.najt.kecon.jsocksproxy.utils.SocketUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in nu.najt.kecon.jsocksproxy.utils.SocketUtilsTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:report (post-unit-test) @ jsocksproxy ---
[INFO] Loading execution data file C:\projects\JSocksProxy\target\jacoco.exec
[INFO] Analyzed bundle 'jsocksproxy' with 21 classes
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:report (report) @ jsocksproxy ---
[INFO] Loading execution data file C:\projects\JSocksProxy\target\jacoco.exec
[INFO] Analyzed bundle 'jsocksproxy' with 21 classes
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ jsocksproxy ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jsocksproxy ---
[INFO] Installing C:\projects\JSocksProxy\target\jsocksproxy-3.0.0-SNAPSHOT.jar to C:\Users\egor\.m2\repository\nu\najt\kecon\jsocksproxy\jsocksproxy\3.0.0-SNAPSHOT\jsocksproxy-3.0.0-SNAPSHOT.jar
[INFO] Installing C:\projects\JSocksProxy\pom.xml to C:\Users\egor\.m2\repository\nu\najt\kecon\jsocksproxy\jsocksproxy\3.0.0-SNAPSHOT\jsocksproxy-3.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.291 s
[INFO] Finished at: 2018-06-03T20:58:45+03:00
[INFO] Final Memory: 17M/269M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
`
